# Generated by Django 2.2.1 on 2019-05-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=10)),
                ('content', models.TextField(null=True)),
                ('public_date', models.DateField(default='2016-02-28')),
            ],
        ),
    ]
